# Generated by Django 3.2.18 on 2023-04-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadAire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amoniaco', models.IntegerField()),
                ('benceno', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('nitrogeno', models.IntegerField()),
                ('monoxido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperaturaC', models.IntegerField()),
                ('temperaturaF', models.IntegerField()),
                ('humedad', models.IntegerField()),
                ('calorC', models.IntegerField()),
                ('calorF', models.IntegerField()),
            ],
        ),
    ]
